### ISSUE TITLE
New Nav Bar

### ISSUE THREAD

**Issue by AxeFontaine** [michael8411/ScoutingWeb#12]
### Overview
Create new navigation bar drawer for use after sign in.

### Tasks
- [x] Display name and email
- [x] Display Sheets, Main, and Admin pages
- [x] Display Admins
- [ ] Add Admins
- [ ] Show if Admins are online
