### ISSUE TITLE
Centralized Component System

### ISSUE THREAD

**Issue by AxeFontaine** [michael8411/ScoutingWeb#3]
### Overview
Setup for how components are going to work in the future

### Task
- [x] Store metadata for each component depending on use (constraints, class, etc.)
- [x] Allow iteration of components for scouting page
- [x] Use Firebase to store component data

**Comment by michael8411** [comment]
Finished centralized component system
