### ISSUE TITLE
Google Sheets Rework 

### ISSUE THREAD

**Issue by AxeFontaine** [michael8411/ScoutingWeb#5]
### Overview
The google sheets implementation is very convoluted right now and needs a rework. 

### Tasks
- [ ] Remove unnecessary JSON files possibly through firebase
- [ ] Fix file setup for better readability
- [ ] Get the order of the questions from the scouting page
- [ ] Export match data (questions/answers) onto google sheets
