### ISSUE TITLE
Forgot Password Page

### ISSUE THREAD

**Issue by AxeFontaine** [michael8411/ScoutingWeb#7]
### Overview
When a user signs up with a non-school email they need a password, we need a page for if the user forgets their password.

### Tasks
- [ ] Create forgot password page
- [ ] Apply page route on button in login page
- [ ] Send an email to the user for them to change their email ( google api )
